In [1]:
import pandas as pd
import nflreadpy as nfl

In [5]:
weekly = nfl.load_player_stats([2025])
weekly

shape: (19_421, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-002345 ┆ A.Rodgers ┆ Aaron     ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 25.66     ┆ 25.66     │
│ 9         ┆           ┆ Rodgers   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002385 ┆ M.Prater  ┆ Matt      ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆           ┆ Prater    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002556 ┆ N.Folk    ┆ Nick Folk ┆ K        ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 5         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002615 ┆ J.Flacco  ┆ Joe       ┆ QB       ┆ … ┆ 0         ┆ 0         ┆ 12.2      ┆ 12.2      │
│ 8         ┆           ┆ Flacco    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-002619 ┆ C.Campbel ┆ Calais    ┆ DE       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 0         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-004069 ┆ W.Campbel ┆ Will      ┆ OT       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 9         ┆ l         ┆ Campbell  ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004071 ┆ C.Woodson ┆ Craig     ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 6         ┆           ┆ Woodson   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ N.Emmanwo ┆ Nick      ┆ SAF      ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 3         ┆ ri        ┆ Emmanwori ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004073 ┆ T.Henders ┆ TreVeyon  ┆ RB       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 7.5       │
│ 4         ┆ on        ┆ Henderson ┆          ┆   ┆           ┆           ┆           ┆           │
│ null      ┆ null      ┆ null      ┆ null     ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
print(type(weekly))
print(weekly.shape)
print(weekly.columns)

<class 'polars.dataframe.frame.DataFrame'>
(19421, 145)
['player_id', 'player_name', 'player_display_name', 'position', 'position_group', 'headshot_url', 'season', 'week', 'season_type', 'game_id', 'team', 'opponent_team', 'completions', 'attempts', 'passing_yards', 'passing_tds', 'passing_interceptions', 'sacks_suffered', 'sack_yards_lost', 'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch', 'passing_first_downs', 'passing_epa', 'passing_cpoe', 'passing_2pt_conversions', 'pacr', 'passing_10', 'passing_16', 'passing_20', 'passing_40', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions', 'rushing_10', 'rushing_12', 'rushing_20', 'rushing_40', 'receptions', 'targets', 'receiving_yards', 'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards', 'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions', 'receiving_10', 'receiving_16', 'receiving_20', 'receiving_40', 'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds', 'def_tackles_solo', 'def_tackles_with_assist', 'def_tackle_assists', 'def_tackles_for_loss', 'def_tackles_for_loss_yards', 'def_fumbles_forced', 'def_sacks', 'def_sack_yards', 'def_qb_hits', 'def_interceptions', 'def_interception_yards', 'def_pass_defended', 'def_tds', 'def_fumbles', 'def_safeties', 'misc_yards', 'fumble_recovery_own', 'fumble_recovery_yards_own', 'fumble_recovery_opp', 'fumble_recovery_yards_opp', 'fumble_recovery_tds', 'penalties', 'penalty_yards', 'fumbles_forced_by_opp', 'fumbles_not_forced', 'fumbles_out_of_bounds', 'fumbles_total', 'fumbles_lost_total', 'punt_returns', 'punt_return_yards', 'kickoff_returns', 'kickoff_return_yards', 'fg_made', 'fg_att', 'fg_missed', 'fg_blocked', 'fg_long', 'fg_pct', 'fg_made_0_19', 'fg_made_20_29', 'fg_made_30_39', 'fg_made_40_49', 'fg_made_50_59', 'fg_made_60_', 'fg_missed_0_19', 'fg_missed_20_29', 'fg_missed_30_39', 'fg_missed_40_49', 'fg_missed_50_59', 'fg_missed_60_', 'fg_made_list', 'fg_missed_list', 'fg_blocked_list', 'fg_made_distance', 'fg_missed_distance', 'fg_blocked_distance', 'pat_made', 'pat_att', 'pat_missed', 'pat_blocked', 'pat_pct', 'gwfg_made', 'gwfg_att', 'gwfg_missed', 'gwfg_blocked', 'gwfg_distance', 'pt_att', 'pt_blocked', 'pt_long', 'pt_yards', 'pt_inside_20', 'pt_out_of_bounds', 'pt_downed', 'pt_touchback', 'pt_fair_caught', 'pt_returned', 'pt_return_yards', 'pt_return_tds', 'pt_net_yards', 'fantasy_points', 'fantasy_points_ppr']

In [14]:
weekly.filter(weekly['position'] == 'WR')

shape: (2_623, 145)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ player_id ┆ player_na ┆ player_di ┆ position ┆ … ┆ pt_return ┆ pt_net_ya ┆ fantasy_p ┆ fantasy_p │
│ ---       ┆ me        ┆ splay_nam ┆ ---      ┆   ┆ _tds      ┆ rds       ┆ oints     ┆ oints_ppr │
│ str       ┆ ---       ┆ e         ┆ str      ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ str       ┆ ---       ┆          ┆   ┆ i32       ┆ i32       ┆ f64       ┆ f64       │
│           ┆           ┆ str       ┆          ┆   ┆           ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 00-003003 ┆ A.Thielen ┆ Adam      ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.0       ┆ 2.0       │
│ 5         ┆           ┆ Thielen   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003027 ┆ K.Allen   ┆ Keenan    ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 12.8      ┆ 19.8      │
│ 9         ┆           ┆ Allen     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003056 ┆ D.Hopkins ┆ DeAndre   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 9.5       ┆ 11.5      │
│ 4         ┆           ┆ Hopkins   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003123 ┆ B.Cooks   ┆ Brandin   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.6       ┆ 5.6       │
│ 6         ┆           ┆ Cooks     ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003138 ┆ D.Adams   ┆ Davante   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 5.1       ┆ 9.1       │
│ 1         ┆           ┆ Adams     ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 00-003854 ┆ J.Smith-N ┆ Jaxon Smi ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.7       ┆ 6.7       │
│ 3         ┆ jigba     ┆ th-Njigba ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003860 ┆ K.Boutte  ┆ Kayshon   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 2.1       ┆ 3.1       │
│ 8         ┆           ┆ Boutte    ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003862 ┆ D.Douglas ┆ DeMario   ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 4.5       ┆ 9.5       │
│ 1         ┆           ┆ Douglas   ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-003875 ┆ J.Bobo    ┆ Jake Bobo ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 0.0       ┆ 0.0       │
│ 2         ┆           ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 00-004013 ┆ K.William ┆ Kyle      ┆ WR       ┆ … ┆ 0         ┆ 0         ┆ 0.7       ┆ 1.7       │
│ 1         ┆ s         ┆ Williams  ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘